//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.WebFresher052023.Domain.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VietNamese {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VietNamese() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.WebFresher052023.Domain.Resource.VietNamese", typeof(VietNamese).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BHTuyen.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy dữ liệu..
        /// </summary>
        public static string DataNotFound {
            get {
                return ResourceManager.GetString("DataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phòng ban &lt;strong&gt;{0}&lt;/strong&gt; đã tồn tại trong hệ thống..
        /// </summary>
        public static string DepartmentCodeConflict {
            get {
                return ResourceManager.GetString("DepartmentCodeConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban không tồn tại..
        /// </summary>
        public static string DepartmentNotExist {
            get {
                return ResourceManager.GetString("DepartmentNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không được truyền danh sách rỗng..
        /// </summary>
        public static string EmptyList {
            get {
                return ResourceManager.GetString("EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã loại tài sản &lt;strong&gt;{0}&lt;/strong&gt; đã tồn tại trong hệ thống..
        /// </summary>
        public static string FixedAssetCategoryCodeConflict {
            get {
                return ResourceManager.GetString("FixedAssetCategoryCodeConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại tài sản không tồn tại..
        /// </summary>
        public static string FixedAssetCategoryNotExist {
            get {
                return ResourceManager.GetString("FixedAssetCategoryNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài sản &lt;strong&gt;{0}&lt;/strong&gt; đã tồn tại trong hệ thống..
        /// </summary>
        public static string FixedAssetCodeConflict {
            get {
                return ResourceManager.GetString("FixedAssetCodeConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài sản không tồn tại..
        /// </summary>
        public static string FixedAssetNotExist {
            get {
                return ResourceManager.GetString("FixedAssetNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa.
        /// </summary>
        public static string NoDelete {
            get {
                return ResourceManager.GetString("NoDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không thể xóa tài sản này..
        /// </summary>
        public static string NoDeleteFixedAsset {
            get {
                return ResourceManager.GetString("NoDeleteFixedAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không thể xóa chứng từ &lt;strong&gt;{0} ({1})&lt;/strong&gt;..
        /// </summary>
        public static string NoDeleteTransferAsset {
            get {
                return ResourceManager.GetString("NoDeleteTransferAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không thể chỉnh sửa tài sản này..
        /// </summary>
        public static string NoUpdateFixedAsset {
            get {
                return ResourceManager.GetString("NoUpdateFixedAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã chừng từ &lt;strong&gt;{0}&lt;/strong&gt; đã tồn tại trong hệ thống. Vui lòng nhập một mã chứng từ khác..
        /// </summary>
        public static string TransferAssetCodeConflict {
            get {
                return ResourceManager.GetString("TransferAssetCodeConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa thêm tài sản điều chuyển..
        /// </summary>
        public static string TransferAssetDetailNotAdd {
            get {
                return ResourceManager.GetString("TransferAssetDetailNotAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài sản &lt;strong&gt;{0}&lt;/strong&gt; đã có phát sinh chứng từ..
        /// </summary>
        public static string TransferAssetExist {
            get {
                return ResourceManager.GetString("TransferAssetExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Chứng từ điều chuyển &lt;strong&gt;{0} ({1})&lt;/strong&gt;.
        /// </summary>
        public static string TransferAssetInfo {
            get {
                return ResourceManager.GetString("TransferAssetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày điều chuyển phải lớn hơn hoặc bằng ngày chứng từ..
        /// </summary>
        public static string TransferDateLaterTransactionDate {
            get {
                return ResourceManager.GetString("TransferDateLaterTransactionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày điều chuyển cập nhật phải lớn hơn hoặc bằng ngày &lt;strong&gt;{0}&lt;/strong&gt;..
        /// </summary>
        public static string TransferDateMin {
            get {
                return ResourceManager.GetString("TransferDateMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày điều chuyển cập nhật phải nằm trong khoảng &lt;strong&gt;{0} ({1}) - {2} ({3})&lt;/strong&gt;..
        /// </summary>
        public static string TransferDateNotInRange {
            get {
                return ResourceManager.GetString("TransferDateNotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày điều chuyển cập nhật phải nhỏ hơn ngày điểu chuyển của chứng từ &lt;strong&gt;{0} ({1})&lt;/strong&gt;..
        /// </summary>
        public static string TransferDateNotLessThanMin {
            get {
                return ResourceManager.GetString("TransferDateNotLessThanMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày điều chuyển phải lớn hơn ngày điểu chuyển của chứng từ &lt;strong&gt;{0} ({1})&lt;/strong&gt;..
        /// </summary>
        public static string TransferDateNotMoreThanMaxCreate {
            get {
                return ResourceManager.GetString("TransferDateNotMoreThanMaxCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày điều chuyển cập nhật phải lớn hơn ngày điểu chuyển của chứng từ &lt;strong&gt;{0} ({1})&lt;/strong&gt;..
        /// </summary>
        public static string TransferDateNotMoreThanMaxUpdate {
            get {
                return ResourceManager.GetString("TransferDateNotMoreThanMaxUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày điều chuyển cập nhật phải nằm trong khoảng &lt;strong&gt;{0} - {1}&lt;/strong&gt;..
        /// </summary>
        public static string TransferDateRange {
            get {
                return ResourceManager.GetString("TransferDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban điều chuyển phải khác phòng ban đang sử dụng..
        /// </summary>
        public static string TransferDepartmentDiffDepartment {
            get {
                return ResourceManager.GetString("TransferDepartmentDiffDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu sử dụng phải lớn hơn hoặc bằng ngày mua..
        /// </summary>
        public static string UsingStartedDateLaterPurchaseDate {
            get {
                return ResourceManager.GetString("UsingStartedDateLaterPurchaseDate", resourceCulture);
            }
        }
    }
}
