--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 8/23/2023 10:05:43 AM
-- Server version: 10.5.20
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE qlts_fresher_core;

--
-- Drop table `document_receiver`
--
DROP TABLE IF EXISTS document_receiver;

--
-- Drop table `receiver`
--
DROP TABLE IF EXISTS receiver;

--
-- Drop table `asset_document`
--
DROP TABLE IF EXISTS asset_document;

--
-- Drop table `fixed_asset`
--
DROP TABLE IF EXISTS fixed_asset;

--
-- Drop table `department`
--
DROP TABLE IF EXISTS department;

--
-- Drop table `fixed_asset_category`
--
DROP TABLE IF EXISTS fixed_asset_category;

--
-- Drop table `document`
--
DROP TABLE IF EXISTS document;

--
-- Drop table `document_detail`
--
DROP TABLE IF EXISTS document_detail;

--
-- Set default database
--
USE qlts_fresher_core;

--
-- Create table `document_detail`
--
CREATE TABLE document_detail (
  document_detail_id char(36) NOT NULL DEFAULT '' COMMENT 'Id chi tiết chứng từ',
  document_detail_code varchar(255) DEFAULT NULL COMMENT 'Mã code của chi tiết chứng từ',
  current_department_id char(36) DEFAULT NULL COMMENT 'Id của phòng ban hiện tại',
  transfer_department_id char(36) DEFAULT NULL COMMENT 'Id của phòng ban chuyển đến',
  description varchar(255) DEFAULT NULL COMMENT 'Lý do điều chuyển',
  created_by varchar(255) DEFAULT NULL COMMENT 'Người tạo bản ghi',
  created_date datetime DEFAULT NULL COMMENT 'Ngày tạo bản ghi',
  modified_by varchar(255) DEFAULT NULL COMMENT 'Người cập nhật bản ghi',
  modified_date datetime DEFAULT NULL COMMENT 'Ngày cập nhật bản ghi',
  PRIMARY KEY (document_detail_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Chi tiết chứng từ';

--
-- Create table `document`
--
CREATE TABLE document (
  document_id char(36) NOT NULL DEFAULT '' COMMENT 'Id của chứng từ',
  document_code varchar(255) DEFAULT NULL COMMENT 'Mã chứng từ',
  transfer_date datetime DEFAULT NULL COMMENT 'Ngày điều chuyển',
  transaction_date datetime DEFAULT NULL COMMENT 'Ngày chứng từ',
  description varchar(255) DEFAULT NULL COMMENT 'Lý do điều chuyển',
  created_by varchar(255) DEFAULT NULL COMMENT 'Người tạo bản ghi',
  created_date datetime DEFAULT NULL COMMENT 'Ngày tạo bản ghi',
  modified_by varchar(255) DEFAULT NULL COMMENT 'Người cập nhật bản ghi',
  modified_date datetime DEFAULT NULL COMMENT 'Ngày cập nhật bản ghi',
  PRIMARY KEY (document_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Thông tin chứng từ';

--
-- Create foreign key
--
ALTER TABLE document
ADD CONSTRAINT FK_document_document_detail_document_detail_id FOREIGN KEY (document_id)
REFERENCES document_detail (document_detail_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `fixed_asset_category`
--
CREATE TABLE fixed_asset_category (
  fixed_asset_category_id char(36) NOT NULL COMMENT 'Id loại tài sản',
  fixed_asset_category_code varchar(50) DEFAULT NULL COMMENT 'Mã loại tài sản',
  fixed_asset_category_name varchar(255) DEFAULT NULL COMMENT 'Tên loại tài sản',
  organization_id char(36) DEFAULT NULL COMMENT 'Id của đơn vị',
  depreciation_rate float DEFAULT NULL COMMENT 'Tỷ lệ hao mòn (%)',
  life_time int(11) DEFAULT NULL COMMENT 'Số năm sử dụng ',
  description varchar(500) DEFAULT NULL COMMENT 'Ghi chú',
  created_by varchar(50) DEFAULT NULL COMMENT 'Người tạo',
  created_date timestamp NULL DEFAULT CURRENT_TIMESTAMP() COMMENT 'Ngày tạo',
  modified_by varchar(50) DEFAULT NULL COMMENT 'Người sửa',
  modified_date timestamp NULL DEFAULT CURRENT_TIMESTAMP() COMMENT 'Ngày sửa',
  PRIMARY KEY (fixed_asset_category_id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 1638,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Loại tài sản';

--
-- Create table `department`
--
CREATE TABLE department (
  department_id char(36) NOT NULL,
  department_code varchar(50) DEFAULT NULL COMMENT 'Mã của phòng ban',
  department_name varchar(255) DEFAULT NULL COMMENT 'Tên phòng ban',
  description varchar(500) DEFAULT NULL COMMENT 'Ghi chú',
  is_parent bit(1) DEFAULT NULL COMMENT 'Có phải là cha không',
  parent_id char(36) DEFAULT NULL COMMENT 'Id phòng ban cha',
  organization_id char(36) DEFAULT NULL COMMENT 'Id của đơn vị',
  created_by varchar(50) DEFAULT NULL COMMENT 'Người tạo',
  created_date timestamp NULL DEFAULT CURRENT_TIMESTAMP() COMMENT 'Ngày tạo',
  modified_by varchar(50) DEFAULT NULL COMMENT 'Người sửa',
  modified_date timestamp NULL DEFAULT CURRENT_TIMESTAMP() COMMENT 'Ngày sửa',
  PRIMARY KEY (department_id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 1638,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Danh mục phòng ban';

--
-- Create table `fixed_asset`
--
CREATE TABLE fixed_asset (
  fixed_asset_id char(36) NOT NULL COMMENT 'Id tài sản',
  fixed_asset_code varchar(100) DEFAULT NULL COMMENT 'Mã tài sản',
  fixed_asset_name varchar(255) DEFAULT NULL COMMENT 'Tên tài sản',
  organization_id char(36) DEFAULT NULL COMMENT 'Id của đơn vị',
  organization_code varchar(50) DEFAULT NULL COMMENT 'Mã đơn vị',
  organization_name varchar(255) DEFAULT NULL COMMENT 'Tên của đơn vị',
  department_id char(36) DEFAULT NULL COMMENT 'Id phòng ban',
  department_code varchar(50) DEFAULT NULL COMMENT 'Mã phòng ban',
  department_name varchar(255) DEFAULT NULL,
  fixed_asset_category_id char(36) DEFAULT NULL COMMENT 'Id loại tài sản',
  fixed_asset_category_code varchar(50) DEFAULT NULL COMMENT 'Mã loại tài sản',
  fixed_asset_category_name varchar(255) DEFAULT NULL COMMENT 'Tên loại tài sản',
  purchase_date timestamp NULL DEFAULT CURRENT_TIMESTAMP() COMMENT 'Ngày mua',
  start_using_date timestamp NULL DEFAULT NULL COMMENT 'Ngày bắt đầu sử dụng',
  cost decimal(19, 4) DEFAULT NULL COMMENT 'nguyên giá',
  quantity int(11) DEFAULT 0 COMMENT 'Số lượng',
  depreciation_rate float DEFAULT NULL COMMENT 'Tỷ lệ hao mòn (%)',
  tracked_year int(11) DEFAULT NULL COMMENT 'Năm bắt đầu theo dõi tài sản trên phần mềm',
  life_time int(11) DEFAULT NULL COMMENT 'Số năm sử dụng ',
  production_year int(11) DEFAULT NULL COMMENT 'Năm sử dụng',
  active bit(1) DEFAULT b'0' COMMENT 'Sử dụng',
  created_by varchar(50) DEFAULT NULL COMMENT 'Người tạo',
  created_date timestamp NULL DEFAULT CURRENT_TIMESTAMP() COMMENT 'Ngày tạo',
  modified_by varchar(50) DEFAULT NULL COMMENT 'Người sửa',
  modified_date timestamp NULL DEFAULT CURRENT_TIMESTAMP() COMMENT 'Ngày sửa',
  PRIMARY KEY (fixed_asset_id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 847,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE fixed_asset
ADD CONSTRAINT FK_fixed_asset_department_department_id FOREIGN KEY (department_id)
REFERENCES department (department_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE fixed_asset
ADD CONSTRAINT FK_fixed_asset_fixed_asset_category_fixed_asset_category_id FOREIGN KEY (fixed_asset_category_id)
REFERENCES fixed_asset_category (fixed_asset_category_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `asset_document`
--
CREATE TABLE asset_document (
  fixed_asset_id char(36) DEFAULT NULL COMMENT 'Id của bảng tài sản',
  document_detail_id char(36) DEFAULT NULL COMMENT 'Id của bảng chi tiết chứng từ'
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Bảng phụ của bảng tài sản và chi tiết chứng từ';

--
-- Create foreign key
--
ALTER TABLE asset_document
ADD CONSTRAINT FK_asset_document_document_detail_document_detail_id FOREIGN KEY (document_detail_id)
REFERENCES document_detail (document_detail_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE asset_document
ADD CONSTRAINT FK_asset_document_fixed_asset_fixed_asset_id FOREIGN KEY (fixed_asset_id)
REFERENCES fixed_asset (fixed_asset_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `receiver`
--
CREATE TABLE receiver (
  receiver_id char(36) NOT NULL DEFAULT '' COMMENT 'Id của người nhận',
  receiver_code varchar(255) DEFAULT NULL COMMENT 'Mã code của người nhận',
  receiver_fullname varchar(255) DEFAULT NULL COMMENT 'Họ tên đầy đủ của người nhận',
  receiver_delegate varchar(255) DEFAULT NULL COMMENT 'Người đại diện nhận',
  receiver_position varchar(255) DEFAULT NULL COMMENT 'Chức vụ của người nhận',
  created_by varchar(255) DEFAULT NULL COMMENT 'Người tạo bản ghi',
  created_date datetime DEFAULT NULL COMMENT 'Ngày tạo bản ghi',
  modified_by varchar(255) DEFAULT NULL COMMENT 'Người cập nhật bản ghi',
  modified_date datetime DEFAULT NULL COMMENT 'Ngày cập nhật bản ghi',
  PRIMARY KEY (receiver_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Người nhận';

--
-- Create table `document_receiver`
--
CREATE TABLE document_receiver (
  document_id char(36) DEFAULT NULL COMMENT 'Khóa ngoại của chứng từ',
  receiver_id char(36) DEFAULT NULL COMMENT 'Khóa ngoại của người nhận',
  priority int(11) DEFAULT NULL COMMENT 'Thứ tự ưu tiên người nhận'
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'bảng trung gian của chứng từ và người nhận';

--
-- Create foreign key
--
ALTER TABLE document_receiver
ADD CONSTRAINT FK_document_receiver_document_document_id FOREIGN KEY (document_id)
REFERENCES document (document_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE document_receiver
ADD CONSTRAINT FK_document_receiver_receiver_receiver_id FOREIGN KEY (receiver_id)
REFERENCES receiver (receiver_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- 
-- Dumping data for table document_detail
--
-- Table qlts_fresher_core.document_detail does not contain any data (it is empty)

-- 
-- Dumping data for table fixed_asset_category
--
-- 
-- Dumping data for table department
--
-- 
-- Dumping data for table receiver
--
-- Table qlts_fresher_core.receiver does not contain any data (it is empty)

-- 
-- Dumping data for table document
--
-- Table qlts_fresher_core.document does not contain any data (it is empty)

-- 
-- Dumping data for table fixed_asset
--
-- 
-- Dumping data for table document_receiver
--
-- Table qlts_fresher_core.document_receiver does not contain any data (it is empty)

-- 
-- Dumping data for table asset_document
--
-- Table qlts_fresher_core.asset_document does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;