/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    MISAButton: typeof import('./components/button/MISAButton.vue')['default']
    MISAChecbox: typeof import('./components/checkbox/MISAChecbox.vue')['default']
    MISACombobox: typeof import('./components/combobox/MISACombobox.vue')['default']
    MISADatePicker: typeof import('./components/date_picker/MISADatePicker.vue')['default']
    MISADropdown: typeof import('./components/dropdown/MISADropdown.vue')['default']
    MISAInput: typeof import('./components/input/MISAInput.vue')['default']
    MISALoading: typeof import('./components/loading/MISALoading.vue')['default']
    MISAPagination: typeof import('./components/pagination/MISAPagination.vue')['default']
    MISAPopup: typeof import('./components/popup/MISAPopup.vue')['default']
    MISASelectInfo: typeof import('./components/select_info/MISASelectInfo.vue')['default']
    MISASidebarItem: typeof import('./components/sidebar_item/MISASidebarItem.vue')['default']
    MISATable: typeof import('./components/table/MISATable.vue')['default']
    MISATableColumn: typeof import('./components/table_column/MISATableColumn.vue')['default']
    MISAToastMessage: typeof import('./components/toast_message/MISAToastMessage.vue')['default']
    MISATooltip: typeof import('./components/tooltip/MISATooltip.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TransferAssetInfo: typeof import('./components/tranfer_asset_info/TransferAssetInfo.vue')['default']
  }
}
